- hosts: localhost
  #become: yes
  tasks:
        - name: install pre-requisites
          pip:
            name:
               - openshift
               - pyyaml
               - kubernetes 
               - urllib3==1.25.11
  
        - name: Deploy K8S Service
          k8s:
            state: present
            namespace: default
            src: /home/ec2-user/project_files/service.yml

        - name: Project
          k8s:
            state: present
            namespace: default
            src: /home/ec2-user/project_files/deployment.yml
