- hosts: localhost
  #become: true
  tasks:
        - name: install pre-requisites
          pip:
            name:
               - openshift
               - pyyaml
               - kubernetes 
               - urllib3==1.26.6
  
        - name: Deploy K8S Service
          k8s:
            state: present
            namespace: default
            src: /root/service.yml

        - name: Project
          k8s:
            state: present
            namespace: default
            src: /root/deployment.yml
